settings:
  orchestrator:
    synchronous: true
    remote: true

parameters:
  user_full_name: Prashant Malge # [First Name(s)] [Last Name]
  links:
    # Medium articles
    - https://medium.com/decodingml/an-end-to-end-framework-for-production-ready-llm-systems-by-building-your-llm-twin-2cc6bb01141f
    - https://medium.com/decodingml/a-real-time-retrieval-system-for-rag-on-social-media-data-9cc01d50a2a0
    - https://medium.com/decodingml/sota-python-streaming-pipelines-for-fine-tuning-llms-and-rag-in-real-time-82eb07795b87
    - https://medium.com/decodingml/the-4-advanced-rag-algorithms-you-must-know-to-implement-5d0c7f1199d2
    - https://medium.com/decodingml/architect-scalable-and-cost-effective-llm-rag-inference-pipelines-73b94ef82a99
    # Substack
    # GitHub repositories  
    - https://github.com/suyodhanj6/llmops-datacollection
    - https://github.com/suyodhanj6/sample-repo-2
    # LinkedIn posts
    - https://linkedin.com/in/prashantmalge/posts/article1
    - https://linkedin.com/in/prashantmalge/posts/article2